### PR TITLE
Refine CMake build system

### PR DESCRIPTION
**Pull request by LuisHsu**
CMake has been refined and can cooperate with umbrella now.

Documents will be added later

### CODE REVIEW

**Comment by LuisHsu** [comment]
Except for really emergency situation, it's our policy to keep histories and not to rewrite them, no matter they are "dirty" or not.
Though these commit seems not clean at all, they are already pushed and regard as existing histories, so I won't rebase them.
All I can do is to make my future commits cleaner.

**Comment by a127a127** [comment]
I will do the merge before review and auto merge. Will be at the [build-system-merged](/ONNC/onnc/tree/build-system-merged) branch.
Sorry for the parallel evolution issues.

**Comment by ffk0716** [comment]
IMO
If no one has depend on your commit yet.
You should make your git history as "clear" as possible.
That means you should merge/split/rewrite your commits for better explanation.

There is no reason to keep a "unreadable" history.

**Comment by LuisHsu** [comment]
Sorry for the misunderstanding of "rewrite history".
I'll do it next time.

**Comment by lubatang** [comment]
There are too many commits and they don't have consistent objective. My suggestion is to separate this merge requests into pieces and explain the actions and intentions of each merge request.

**Comment by LuisHsu** [comment]
OK, I'll close this request and make it better.

**Pull request closed without merging**
